import { useState, useEffect } from 'react';

import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css';

import PokemonCard from '@/components/PokemonCard/PokemonCard';
import PokemonViewer from '@/components/PokemonViewer/PokemonViewer';

export const getStaticProps = async (context) => {
	const res = await fetch('http://localhost:5000/api/pokemon/all');
	const data = await res.json();

	return {
		props: { pList: data },
	}
}

export default function Home({ pList }) {

	const [pokemonList, setPokemonList] = useState(pList);
	const [selectedHref, setSelectedHref] = useState('');
	const [pokemonData, setPokemonData] = useState({});

	const fetchPokemonData = async href => {
		if(!href) return {};
		const res = await fetch(`http://localhost:5000/api/pokemon?href=${href}`);
		return await res.json();
	}

	useEffect(() => {
		fetchPokemonData(selectedHref)
			.then(data => {
				console.log(data);
				setPokemonData(data);
			})
			.catch(err => console.log(err));
	}, [selectedHref]);

	return (
		<>
			<Head>
				<title>Minimalistic Pokedex</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.main}>
				<div className={styles.pokemon_grid}>
					{
						pokemonList.map((pokemon, i) => {
							return <PokemonCard 
								key={i.toString()} 
								{...pokemon}
								setSelectedHref={setSelectedHref}/>
						})
					}
				</div>
				<div className={styles.pokemon_viewer_wrapper}>
					<h2>Minimalistic Pokedex</h2>
					<PokemonViewer {...pokemonData}/>
				</div>
			</div>
		</>
	)
}
